#!/bin/sh

# Add this function to your .bashrc or .zshrc
print_commit_table() {
    echo -e "\n| Commit Type | Title                    | Description                                                                                                 | Emoji  |"
    echo -e "| ----------- | ------------------------ | ----------------------------------------------------------------------------------------------------------- |:------:|"
    echo -e "| \`feat\`      | Features                 | A new feature                                                                                               | ✨     |"
    echo -e "| \`fix\`       | Bug Fixes                | A bug Fix                                                                                                   | 🐛     |"
    echo -e "| \`docs\`      | Documentation            | Documentation only changes                                                                                  | 📚     |"
    echo -e "| \`style\`     | Styles                   | Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)      | 💎     |"
    echo -e "| \`refactor\`  | Code Refactoring         | A code change that neither fixes a bug nor adds a feature                                                   | 📦     |"
    echo -e "| \`perf\`      | Performance Improvements | A code change that improves performance                                                                     | 🚀     |"
    echo -e "| \`test\`      | Tests                    | Adding missing tests or correcting existing tests                                                           | 🚨     |"
    echo -e "| \`build\`     | Builds                   | Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)         | 🛠     |"
    echo -e "| \`ci\`        | Continuous Integrations  | Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs) | 👷     |"
    echo -e "| \`chore\`     | Chores                   | Other changes that don't modify src or test files                                                           | 🔧     |"
    echo -e "| \`revert\`    | Reverts                  | Reverts a previous commit                                                                                   | 🗑     |\n"
}
